import { useEffect, useState, useRef, useCallback } from "react";
import { useNavigate } from "react-router-dom";
import { reviewService } from "../services/reviewService";
import type { ExtractionResult } from "@/features/upload/services/extractionService";
import type { VendorSearchResult, POSearchResult } from "@/types/documents";

import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import {
  Card,
  CardContent,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Badge } from "@/components/ui/badge";
import { LoadingSpinner } from "@/components/common/LoadingSpinner";
import { DocumentViewer } from "@/components/common/DocumentViewer";
import {
  ArrowLeft,
  Send,
  Plus,
  Trash2,
  X,
  FileText,
  FileSpreadsheet,
  AlertCircle,
  CheckCircle2,
  Search,
} from "lucide-react";

interface LineItemForm {
  line_number: number;
  item_code: string;
  item_description: string;
  quantity: string;
  unit_price: string;
  total_price: string;
}

function normalizeErrorDetail(detail: unknown): string | null {
  if (typeof detail === "string" && detail.trim()) {
    return detail;
  }

  if (Array.isArray(detail)) {
    const messages = detail
      .map((entry) => {
        if (typeof entry === "string") {
          return entry;
        }

        if (entry && typeof entry === "object") {
          const record = entry as Record<string, unknown>;
          const msg = typeof record.msg === "string" ? record.msg : "Validation error";
          const locValue = record.loc;
          const loc = Array.isArray(locValue)
            ? locValue.map(String).join(".")
            : typeof locValue === "string"
              ? locValue
              : "";
          return loc ? `${loc}: ${msg}` : msg;
        }

        return null;
      })
      .filter((msg): msg is string => Boolean(msg && msg.trim()));

    return messages.length ? messages.join("; ") : null;
  }

  if (detail && typeof detail === "object") {
    const record = detail as Record<string, unknown>;
    if (typeof record.msg === "string" && record.msg.trim()) {
      return record.msg;
    }
    try {
      return JSON.stringify(detail);
    } catch {
      return "Validation failed";
    }
  }

  return null;
}

function getErrorMessage(err: unknown, fallback: string): string {
  const axiosErr = err as {
    response?: { data?: { detail?: unknown } };
    message?: string;
  };

  const detailMessage = normalizeErrorDetail(axiosErr.response?.data?.detail);
  if (detailMessage) {
    return detailMessage;
  }

  return axiosErr.message ?? fallback;
}

/* ------------------------------------------------------------------ */
/*  Single document review form (rendered per tab)                    */
/* ------------------------------------------------------------------ */

function DocumentReviewForm({
  item,
  onSubmitted,
  onDeleted,
}: {
  item: ExtractionResult;
  onSubmitted: () => void;
  onDeleted: (message: string) => void;
}) {
  const isInvoice = (item.document_type as string) === "invoice";
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const extractedData = (item.extracted_data ?? {}) as Record<string, any>;
  const score = item.score;
  const fileUrl = item.file_url;
  const storedRecord = item.stored_record!;
  const poStatus = String(extractedData?.status ?? "PENDING").toUpperCase();
  const canDeletePO = !isInvoice && poStatus === "PENDING";

  // Detect auto-generated IDs: either flagged by backend or matching the AUTO- prefix pattern
  const autoGeneratedFields = item.auto_generated_fields ?? [];
  const isInvoiceNumAutoGenerated =
    isInvoice &&
    (autoGeneratedFields.includes("invoice_number") ||
      String(extractedData.invoice_number ?? "").startsWith("AUTO-INV-"));
  const isPONumAutoGenerated =
    !isInvoice &&
    (autoGeneratedFields.includes("po_number") ||
      String(extractedData.po_number ?? "").startsWith("AUTO-PO-"));
  const criticalFieldsMissing: string[] = score?.critical_fields_missing ?? [];

  const [form, setForm] = useState(() => ({
    invoice_number: String(extractedData?.invoice_number ?? ""),
    po_number: String(extractedData?.po_number ?? item?.stored_record?.po_number ?? ""),
    po_references: (() => {
      if (Array.isArray(extractedData?.po_references)) {
        return extractedData.po_references.map(String);
      }
      if (extractedData?.reference_po_number) {
        return [String(extractedData.reference_po_number)];
      }
      return [] as string[];
    })(),
    vendor_name: String(extractedData?.vendor_name ?? ""),
    vendor_email: String(extractedData?.vendor_email ?? ""),
    vendor_phone: String(extractedData?.vendor_phone ?? ""),
    vendor_address: String(extractedData?.vendor_address ?? ""),
    vendor_tax_id: String(extractedData?.vendor_tax_id ?? ""),
    currency: String(extractedData?.currency ?? "USD"),
    due_date: String(extractedData?.due_date ?? ""),
    po_date: String(extractedData?.po_date ?? ""),
    subtotal: String(extractedData?.subtotal ?? "0"),
    tax_amount: String(extractedData?.tax_amount ?? "0"),
    discount_amount: String(extractedData?.discount_amount ?? "0"),
    total_amount: String(extractedData?.total_amount ?? "0"),
  }));

  const [lineItems, setLineItems] = useState<LineItemForm[]>(() =>
    ((extractedData.line_items as unknown[]) ?? []).map(
      (raw: unknown, idx: number) => {
        const li = raw as Record<string, unknown>;
        return {
          line_number: Number(li.line_number ?? idx + 1),
          item_code: String(li.item_code ?? ""),
          item_description: String(li.item_description ?? ""),
          quantity: String(li.quantity ?? ""),
          unit_price: String(li.unit_price ?? ""),
          total_price: String(li.total_price ?? ""),
        };
      },
    ),
  );

  const [submitting, setSubmitting] = useState(false);
  const [submitError, setSubmitError] = useState<string | null>(null);
  const [deleting, setDeleting] = useState(false);
  const [deleteError, setDeleteError] = useState<string | null>(null);
  const [showDeleteConfirm, setShowDeleteConfirm] = useState(false);

  // ── Vendor search state ──
  const [vendorQuery, setVendorQuery] = useState(String(extractedData.vendor_name ?? ""));
  const [vendorResults, setVendorResults] = useState<VendorSearchResult[]>([]);
  const [selectedVendor, setSelectedVendor] = useState<VendorSearchResult | null>(null);
  const [showVendorDropdown, setShowVendorDropdown] = useState(false);
  const vendorRef = useRef<HTMLDivElement>(null);

  // ── PO search state (multi-select) ──
  const [poQuery, setPoQuery] = useState("");
  const [poResults, setPoResults] = useState<POSearchResult[]>([]);
  const [selectedPOs, setSelectedPOs] = useState<POSearchResult[]>([]);
  const [showPODropdown, setShowPODropdown] = useState(false);
  const poRef = useRef<HTMLDivElement>(null);

  // Debounced vendor search
  const vendorTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const handleVendorSearch = useCallback((query: string) => {
    setVendorQuery(query);
    setSelectedVendor(null);
    if (vendorTimerRef.current) clearTimeout(vendorTimerRef.current);
    if (query.trim().length < 1) {
      setVendorResults([]);
      setShowVendorDropdown(false);
      return;
    }
    vendorTimerRef.current = setTimeout(async () => {
      const results = await reviewService.searchVendors(query.trim());
      setVendorResults(results);
      setShowVendorDropdown(results.length > 0);
    }, 300);
  }, []);

  // Debounced PO search
  const poTimerRef = useRef<ReturnType<typeof setTimeout> | null>(null);
  const handlePOSearch = useCallback((query: string) => {
    setPoQuery(query);
    if (poTimerRef.current) clearTimeout(poTimerRef.current);
    if (query.trim().length < 1) {
      setPoResults([]);
      setShowPODropdown(false);
      return;
    }
    poTimerRef.current = setTimeout(async () => {
      const results = await reviewService.searchPurchaseOrders(query.trim());
      setPoResults(results);
      setShowPODropdown(results.length > 0);
    }, 300);
  }, []);

  // Select a vendor
  const selectVendor = (v: VendorSearchResult) => {
    setSelectedVendor(v);
    setVendorQuery(v.vendor_name ?? "");
    setShowVendorDropdown(false);
    setForm((prev) => ({
      ...prev,
      vendor_name: v.vendor_name ?? "",
      vendor_email: v.vendor_email ?? "",
      vendor_phone: v.vendor_phone ?? "",
      vendor_address: v.vendor_address ?? "",
      vendor_tax_id: v.gst_number ?? "",
    }));
  };

  // Add a PO to the list — also auto-fill vendor from first PO
  const addPO = (po: POSearchResult) => {
    if (form.po_references.includes(po.po_number)) return;
    setSelectedPOs((prev) => [...prev, po]);
    setForm((prev) => ({
      ...prev,
      po_references: [...prev.po_references, po.po_number],
    }));
    setPoQuery("");
    setShowPODropdown(false);
    // Auto-fill vendor from first PO
    if (form.po_references.length === 0 && po.vendor) {
      selectVendor(po.vendor);
    }
  };

  // Remove a PO from the list
  const removePO = (poNumber: string) => {
    setSelectedPOs((prev) => prev.filter((p) => p.po_number !== poNumber));
    setForm((prev) => ({
      ...prev,
      po_references: prev.po_references.filter((ref) => ref !== poNumber),
    }));
  };

  // Auto-search vendor on mount if extracted vendor_name exists
  useEffect(() => {
    if (extractedData.vendor_name) {
      reviewService.searchVendors(String(extractedData.vendor_name)).then((results) => {
        if (results.length === 1) {
          selectVendor(results[0]);
        } else if (results.length > 1) {
          const exact = results.find(
            (v) => v.vendor_name?.toLowerCase() === String(extractedData.vendor_name).toLowerCase()
          );
          if (exact) selectVendor(exact);
        }
      }).catch(() => {});
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Auto-resolve extracted PO references on mount
  useEffect(() => {
    if (isInvoice && form.po_references.length > 0) {
      Promise.all(
        form.po_references.map(async (ref) => {
          try {
            const results = await reviewService.searchPurchaseOrders(ref);
            return results.find(
              (r) => r.po_number.toLowerCase() === ref.toLowerCase()
            ) || null;
          } catch {
            return null;
          }
        })
      ).then((resolved) => {
        const found = resolved.filter(
          (r): r is POSearchResult => r !== null
        );
        if (found.length > 0) {
          setSelectedPOs(found);
          if (found[0].vendor) selectVendor(found[0].vendor);
        }
      });
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // Close dropdowns on outside click
  useEffect(() => {
    const handler = (e: MouseEvent) => {
      if (vendorRef.current && !vendorRef.current.contains(e.target as Node))
        setShowVendorDropdown(false);
      if (poRef.current && !poRef.current.contains(e.target as Node))
        setShowPODropdown(false);
    };
    document.addEventListener("mousedown", handler);
    return () => document.removeEventListener("mousedown", handler);
  }, []);

  const updateField = (field: string, value: string) =>
    setForm((prev) => ({ ...prev, [field]: value }));

  const updateLineItem = (
    index: number,
    field: keyof LineItemForm,
    value: string | number,
  ) =>
    setLineItems((prev) =>
      prev.map((li, i) => (i === index ? { ...li, [field]: value } : li)),
    );

  const addLineItem = () =>
    setLineItems((prev) => [
      ...prev,
      {
        line_number: prev.length + 1,
        item_code: "",
        item_description: "",
        quantity: "",
        unit_price: "",
        total_price: "",
      },
    ]);

  const removeLineItem = (index: number) =>
    setLineItems((prev) => prev.filter((_, i) => i !== index));

  const handleSubmit = async () => {
    setSubmitting(true);
    setSubmitError(null);

    if (!isInvoice && !form.vendor_email?.trim()) {
      setSubmitError("Vendor Email is required for Purchase Orders.");
      setSubmitting(false);
      return;
    }

    try {
      const items = lineItems.map((li) => ({
        line_number: li.line_number,
        item_code: li.item_code || undefined,
        item_description: li.item_description || undefined,
        quantity: li.quantity ? Number(li.quantity) : undefined,
        unit_price: li.unit_price ? Number(li.unit_price) : undefined,
        total_price: li.total_price ? Number(li.total_price) : undefined,
      }));

      if (isInvoice) {
        if (form.po_references.length === 0) {
          setSubmitError("At least one PO reference is required for invoices.");
          setSubmitting(false);
          return;
        }
        // Store PO references in localStorage for pipeline consistency
        localStorage.setItem(
          "invoice_po_references",
          JSON.stringify(form.po_references)
        );
        await reviewService.submitInvoiceReview(storedRecord.id, {
          invoice_number: form.invoice_number || undefined,
          po_references: form.po_references,
          vendor_name: form.vendor_name || undefined,
          vendor_email: form.vendor_email || undefined,
          vendor_phone: form.vendor_phone || undefined,
          vendor_address: form.vendor_address || undefined,
          vendor_tax_id: form.vendor_tax_id || undefined,
          currency: form.currency || undefined,
          due_date: form.due_date || undefined,
          subtotal: form.subtotal ? Number(form.subtotal) : undefined,
          tax_amount: form.tax_amount ? Number(form.tax_amount) : undefined,
          discount_amount: form.discount_amount
            ? Number(form.discount_amount)
            : undefined,
          total_amount: form.total_amount
            ? Number(form.total_amount)
            : undefined,
          line_items: items,
        });
      } else {
        await reviewService.submitPOReview(storedRecord.id, {
          po_number: form.po_number || undefined,
          vendor_name: form.vendor_name || undefined,
          vendor_email: form.vendor_email || undefined,
          vendor_phone: form.vendor_phone || undefined,
          vendor_address: form.vendor_address || undefined,
          vendor_tax_id: form.vendor_tax_id || undefined,
          currency: form.currency || undefined,
          po_date: form.po_date || undefined,
          subtotal: form.subtotal ? Number(form.subtotal) : undefined,
          tax_amount: form.tax_amount ? Number(form.tax_amount) : undefined,
          discount_amount: form.discount_amount
            ? Number(form.discount_amount)
            : undefined,
          total_amount: form.total_amount
            ? Number(form.total_amount)
            : undefined,
          line_items: items,
        });
      }

      onSubmitted();
    } catch (err: unknown) {
      setSubmitError(getErrorMessage(err, "Submission failed"));
    } finally {
      setSubmitting(false);
    }
  };

  const handleDeletePurchaseOrder = async () => {
    if (!storedRecord?.id) {
      return;
    }

    setDeleting(true);
    setDeleteError(null);

    try {
      const response = await reviewService.deletePurchaseOrder(storedRecord.id);
      setShowDeleteConfirm(false);
      onDeleted(response.message || "Purchase Order deleted successfully");
    } catch (err: unknown) {
      setDeleteError(getErrorMessage(err, "Failed to delete purchase order"));
    } finally {
      setDeleting(false);
    }
  };

  return (
    <>
    <div className="space-y-4">
      {/* {score ? (
        <div className="flex items-center gap-2 justify-end">
          <span
            className={`text-lg font-bold ${
              score.requires_review ? "text-amber-600" : "text-emerald-600"
            }`}
          >
            {score.percentage}%
          </span>
          <Badge variant={score.requires_review ? "warning" : "success"}>
            {score.requires_review ? "Review Required" : "Good Quality"}
          </Badge>
        </div>
      ) : (
        <div className="flex items-center gap-2 justify-end animate-pulse">
          <div className="h-6 w-12 rounded bg-muted" />
          <div className="h-5 w-24 rounded-full bg-muted" />
        </div>
      )} */}

      {submitError && (
        <div className="flex items-start gap-3 rounded-lg border border-destructive/50 bg-destructive/5 px-4 py-3">
          <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-destructive">
              Submission Failed
            </p>
            <p className="text-sm text-muted-foreground mt-0.5">
              {submitError}
            </p>
          </div>
        </div>
      )}

      {deleteError && (
        <div className="flex items-start gap-3 rounded-lg border border-destructive/50 bg-destructive/5 px-4 py-3">
          <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-destructive">
              Delete Failed
            </p>
            <p className="text-sm text-muted-foreground mt-0.5">
              {deleteError}
            </p>
          </div>
        </div>
      )}

      {/* ── Auto-generated ID warning ── */}
      {(isInvoiceNumAutoGenerated || isPONumAutoGenerated) && (
        <div className="flex items-start gap-3 rounded-lg border border-amber-400 bg-amber-50 px-4 py-3">
          <AlertCircle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-amber-800">
              {isInvoiceNumAutoGenerated ? "Invoice Number" : "PO Number"} Was Auto-Generated
            </p>
            <p className="text-sm text-amber-700 mt-0.5">
              The {isInvoiceNumAutoGenerated ? "invoice number" : "PO number"} could not be
              extracted from the document. A temporary placeholder (
              <span className="font-mono font-semibold">
                {isInvoiceNumAutoGenerated
                  ? String(extractedData.invoice_number ?? "")
                  : String(extractedData.po_number ?? "")}
              </span>
              ) has been assigned. <strong>Please replace it with the correct value</strong> before
              submitting.
            </p>
          </div>
        </div>
      )}

      {/* ── Missing critical fields warning ── */}
      {criticalFieldsMissing.length > 0 && (
        <div className="flex items-start gap-3 rounded-lg border border-amber-400 bg-amber-50 px-4 py-3">
          <AlertCircle className="h-5 w-5 text-amber-600 shrink-0 mt-0.5" />
          <div>
            <p className="text-sm font-semibold text-amber-800">Human Verification Required</p>
            <p className="text-sm text-amber-700 mt-0.5">
              The following critical fields were not extracted and must be filled in:
            </p>
            <ul className="mt-1 ml-4 list-disc text-sm text-amber-700">
              {criticalFieldsMissing.map((f) => (
                <li key={f} className="capitalize">
                  {f.replace(/_/g, " ")}
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      <div className="flex flex-col lg:flex-row gap-6">
        {/* LEFT: Document Preview */}
        <div className="lg:w-3/5 min-w-0">
          <div className="lg:sticky lg:top-4 h-[calc(100vh-10rem)] min-h-[400px] border rounded-xl shadow-sm overflow-hidden bg-background">
             <DocumentViewer
                fileUrl={fileUrl ?? null}
                title="Document Preview"
             />
          </div>
        </div>

        {/* RIGHT: Editable Form */}
        <div className="lg:w-2/5 space-y-5 pb-8 min-w-0">
          <Card className="border shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider flex items-center gap-2">
                {isInvoice ? (
                  <FileText className="h-4 w-4" />
                ) : (
                  <FileSpreadsheet className="h-4 w-4" />
                )}
                Document Info
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {isInvoice ? (
                <>
                  <div className="space-y-1.5">
                    <Label htmlFor="invoice_number" className={isInvoiceNumAutoGenerated ? "text-amber-700" : ""}>
                      Invoice Number
                      {isInvoiceNumAutoGenerated && (
                        <span className="ml-2 text-xs font-normal text-amber-600">(auto-generated — please correct)</span>
                      )}
                    </Label>
                    <Input
                      id="invoice_number"
                      value={form.invoice_number}
                      onChange={(e) =>
                        updateField("invoice_number", e.target.value)
                      }
                      className={isInvoiceNumAutoGenerated ? "border-amber-400 bg-amber-50/50 focus-visible:ring-amber-400" : ""}
                    />
                  </div>
                  <div className="space-y-1.5" ref={poRef}>
                    <Label htmlFor="po_references">
                      PO References{" "}
                      <span className="text-destructive">*</span>
                    </Label>
                    {/* Selected POs as tags */}
                    {form.po_references.length > 0 && (
                      <div className="flex flex-wrap gap-1.5 mb-2">
                        {form.po_references.map((ref) => (
                          <Badge
                            key={ref}
                            variant="secondary"
                            className="gap-1 pr-1"
                          >
                            {ref}
                            <button
                              type="button"
                              onClick={() => removePO(ref)}
                              className="ml-1 hover:text-destructive"
                            >
                              <X className="h-3 w-3" />
                            </button>
                          </Badge>
                        ))}
                      </div>
                    )}
                    <div className="relative">
                      <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        id="po_references"
                        role="combobox"
                        aria-expanded={showPODropdown}
                        aria-haspopup="listbox"
                        aria-autocomplete="list"
                        aria-controls="po-search-listbox"
                        value={poQuery}
                        onChange={(e) => handlePOSearch(e.target.value)}
                        onFocus={() => {
                          if (poResults.length > 0) setShowPODropdown(true);
                        }}
                        placeholder="Search PO number to add…"
                        className={`pl-8 ${
                          form.po_references.length === 0
                            ? "border-amber-400"
                            : ""
                        }`}
                      />
                      {showPODropdown && poResults.length > 0 && (
                        <div
                          id="po-search-listbox"
                          role="listbox"
                          className="absolute z-50 mt-1 w-full bg-background border rounded-lg shadow-lg max-h-48 overflow-y-auto"
                        >
                          {poResults
                            .filter(
                              (po) =>
                                !form.po_references.includes(po.po_number)
                            )
                            .map((po) => (
                              <button
                                key={po.id}
                                type="button"
                                role="option"
                                className="w-full text-left px-3 py-2 text-sm hover:bg-muted/50 flex justify-between items-center"
                                onClick={() => addPO(po)}
                              >
                                <span className="font-medium">
                                  {po.po_number}
                                </span>
                                <span className="text-xs text-muted-foreground">
                                  {po.vendor?.vendor_name ?? ""}
                                </span>
                              </button>
                            ))}
                        </div>
                      )}
                    </div>
                    {selectedPOs.length > 0 && (
                      <p className="text-xs text-emerald-600 flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        {selectedPOs.length} PO{selectedPOs.length > 1 ? "s" : ""}{" "}
                        linked
                      </p>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="currency">Currency</Label>
                      <Input
                        id="currency"
                        value={form.currency}
                        onChange={(e) =>
                          updateField("currency", e.target.value)
                        }
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label htmlFor="due_date">Due Date</Label>
                      <Input
                        id="due_date"
                        type="date"
                        value={form.due_date}
                        onChange={(e) =>
                          updateField("due_date", e.target.value)
                        }
                      />
                    </div>
                  </div>
                </>
              ) : (
                <>
                  <div className="space-y-1.5">
                    <Label htmlFor="po_number" className={isPONumAutoGenerated ? "text-amber-700" : ""}>
                      PO Number
                      {isPONumAutoGenerated && (
                        <span className="ml-2 text-xs font-normal text-amber-600">(auto-generated — please correct)</span>
                      )}
                    </Label>
                    <Input
                      id="po_number"
                      value={form.po_number}
                      onChange={(e) =>
                        updateField("po_number", e.target.value)
                      }
                      className={isPONumAutoGenerated ? "border-amber-400 bg-amber-50/50 focus-visible:ring-amber-400" : ""}
                    />
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="currency">Currency</Label>
                      <Input
                        id="currency"
                        value={form.currency}
                        onChange={(e) =>
                          updateField("currency", e.target.value)
                        }
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label htmlFor="po_date">PO Date</Label>
                      <Input
                        id="po_date"
                        type="date"
                        value={form.po_date}
                        onChange={(e) =>
                          updateField("po_date", e.target.value)
                        }
                      />
                    </div>
                  </div>
                </>
              )}
            </CardContent>
          </Card>

          <Card className="border shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                Vendor Info
              </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              {isInvoice ? (
                <>
                  <div className="space-y-1.5" ref={vendorRef}>
                    <Label htmlFor="vendor_name">Vendor Name</Label>
                    <div className="relative">
                      <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        id="vendor_name"
                        role="combobox"
                        aria-expanded={showVendorDropdown}
                        aria-haspopup="listbox"
                        aria-autocomplete="list"
                        aria-controls="vendor-search-listbox"
                        value={vendorQuery}
                        onChange={(e) => handleVendorSearch(e.target.value)}
                        onFocus={() => {
                          if (vendorResults.length > 0) setShowVendorDropdown(true);
                        }}
                        placeholder="Search vendor…"
                        className="pl-8"
                      />
                      {showVendorDropdown && vendorResults.length > 0 && (
                        <div
                          id="vendor-search-listbox"
                          role="listbox"
                          className="absolute z-50 mt-1 w-full bg-background border rounded-lg shadow-lg max-h-48 overflow-y-auto"
                        >
                          {vendorResults.map((v) => (
                            <button
                              key={v.id}
                              type="button"
                              role="option"
                              className="w-full text-left px-3 py-2 text-sm hover:bg-muted/50"
                              onClick={() => selectVendor(v)}
                            >
                              <span className="font-medium">{v.vendor_name}</span>
                              {v.vendor_email && (
                                <span className="ml-2 text-xs text-muted-foreground">
                                  {v.vendor_email}
                                </span>
                              )}
                            </button>
                          ))}
                        </div>
                      )}
                    </div>
                    {selectedVendor && (
                      <p className="text-xs text-emerald-600 flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        Selected: {selectedVendor.vendor_name}
                      </p>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="vendor_email">Email</Label>
                      <Input
                        id="vendor_email"
                        type="email"
                        value={form.vendor_email}
                        readOnly
                        className="bg-muted/30"
                        aria-describedby="vendor-readonly-hint"
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label htmlFor="vendor_phone">Phone</Label>
                      <Input
                        id="vendor_phone"
                        value={form.vendor_phone}
                        readOnly
                        className="bg-muted/30"
                        aria-describedby="vendor-readonly-hint"
                      />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="vendor_address">Address</Label>
                    <Input
                      id="vendor_address"
                      value={form.vendor_address}
                      readOnly
                      className="bg-muted/30"
                      aria-describedby="vendor-readonly-hint"
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="vendor_tax_id">Tax / GST ID</Label>
                    <Input
                      id="vendor_tax_id"
                      value={form.vendor_tax_id}
                      readOnly
                      className="bg-muted/30"
                      aria-describedby="vendor-readonly-hint"
                    />
                  </div>
                  <p id="vendor-readonly-hint" className="text-xs text-muted-foreground italic">
                    These fields are auto-filled from the selected vendor and cannot be edited directly.
                  </p>
                </>
              ) : (
                <>
                  <div className="space-y-1.5" ref={vendorRef}>
                    <Label htmlFor="vendor_name">Vendor Name</Label>
                    <div className="relative">
                      <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 h-4 w-4 text-muted-foreground" />
                      <Input
                        id="vendor_name"
                        role="combobox"
                        aria-expanded={showVendorDropdown}
                        aria-haspopup="listbox"
                        aria-autocomplete="list"
                        aria-controls="vendor-search-listbox"
                        value={vendorQuery}
                        onChange={(e) => handleVendorSearch(e.target.value)}
                        onFocus={() => {
                          if (vendorResults.length > 0) setShowVendorDropdown(true);
                        }}
                        placeholder="Search vendor by name or email…"
                        className="pl-8"
                      />
                      {showVendorDropdown && (
                        <div
                          id="vendor-search-listbox"
                          role="listbox"
                          className="absolute z-50 mt-1 w-full bg-background border rounded-lg shadow-lg max-h-48 overflow-y-auto"
                        >
                          {vendorResults.length > 0 ? (
                            vendorResults.map((v) => (
                              <button
                                key={v.id}
                                type="button"
                                role="option"
                                className="w-full text-left px-3 py-2 text-sm hover:bg-muted/50"
                                onClick={() => selectVendor(v)}
                              >
                                <span className="font-medium">{v.vendor_name}</span>
                                {v.vendor_email && (
                                  <span className="ml-2 text-xs text-muted-foreground">
                                    {v.vendor_email}
                                  </span>
                                )}
                              </button>
                            ))
                          ) : null}
                          {/* Create new vendor option */}
                          {vendorQuery.trim().length > 0 && (
                            <button
                              type="button"
                              className="w-full text-left px-3 py-2 text-sm hover:bg-muted/50 border-t flex items-center gap-2 text-primary"
                              onClick={() => {
                                setSelectedVendor(null);
                                setShowVendorDropdown(false);
                                setForm((prev) => ({
                                  ...prev,
                                  vendor_name: vendorQuery.trim(),
                                }));
                              }}
                            >
                              <Plus className="h-3.5 w-3.5" />
                              Create new vendor "{vendorQuery.trim()}"
                            </button>
                          )}
                        </div>
                      )}
                    </div>
                    {selectedVendor && (
                      <p className="text-xs text-emerald-600 flex items-center gap-1">
                        <CheckCircle2 className="h-3 w-3" />
                        Selected: {selectedVendor.vendor_name}
                      </p>
                    )}
                    {!selectedVendor && form.vendor_name && (
                      <p className="text-xs text-amber-600 flex items-center gap-1">
                        <AlertCircle className="h-3 w-3" />
                        New vendor — fill in details below
                      </p>
                    )}
                  </div>
                  <div className="grid grid-cols-2 gap-4">
                    <div className="space-y-1.5">
                      <Label htmlFor="vendor_email">
                        Email <span className="text-destructive">*</span>
                      </Label>
                      <Input
                        id="vendor_email"
                        type="email"
                        value={form.vendor_email}
                        readOnly={!!selectedVendor}
                        className={selectedVendor ? "bg-muted/30" : ""}
                        onChange={(e) =>
                          updateField("vendor_email", e.target.value)
                        }
                      />
                    </div>
                    <div className="space-y-1.5">
                      <Label htmlFor="vendor_phone">Phone</Label>
                      <Input
                        id="vendor_phone"
                        value={form.vendor_phone}
                        readOnly={!!selectedVendor}
                        className={selectedVendor ? "bg-muted/30" : ""}
                        onChange={(e) =>
                          updateField("vendor_phone", e.target.value)
                        }
                      />
                    </div>
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="vendor_address">Address</Label>
                    <Input
                      id="vendor_address"
                      value={form.vendor_address}
                      readOnly={!!selectedVendor}
                      className={selectedVendor ? "bg-muted/30" : ""}
                      onChange={(e) =>
                        updateField("vendor_address", e.target.value)
                      }
                    />
                  </div>
                  <div className="space-y-1.5">
                    <Label htmlFor="vendor_tax_id">Tax / GST ID</Label>
                    <Input
                      id="vendor_tax_id"
                      value={form.vendor_tax_id}
                      readOnly={!!selectedVendor}
                      className={selectedVendor ? "bg-muted/30" : ""}
                      onChange={(e) =>
                        updateField("vendor_tax_id", e.target.value)
                      }
                    />
                  </div>
                  {selectedVendor && (
                    <p className="text-xs text-muted-foreground italic">
                      Fields auto-filled from selected vendor. Search again to change.
                    </p>
                  )}
                </>
              )}
            </CardContent>
          </Card>

          <Card className="border shadow-sm">
            <CardHeader className="pb-3">
              <div className="flex items-center justify-between">
                <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                  Line Items
                  <span className="ml-2 text-xs font-normal normal-case">
                    ({lineItems.length})
                  </span>
                </CardTitle>
                <Button variant="outline" size="sm" onClick={addLineItem}>
                  <Plus className="h-3.5 w-3.5 mr-1" />
                  Add Row
                </Button>
              </div>
            </CardHeader>
            <CardContent className="p-0">
              <div className="overflow-x-auto">
                <table className="w-full text-sm">
                  <thead>
                    <tr className="border-y bg-muted/50">
                      <th className="text-left px-3 py-2 font-medium text-muted-foreground w-12">
                        #
                      </th>
                      <th className="text-left px-3 py-2 font-medium text-muted-foreground w-24">
                        Code
                      </th>
                      <th className="text-left px-3 py-2 font-medium text-muted-foreground">
                        Description
                      </th>
                      <th className="text-right px-3 py-2 font-medium text-muted-foreground w-20">
                        Qty
                      </th>
                      <th className="text-right px-3 py-2 font-medium text-muted-foreground w-24">
                        Unit Price
                      </th>
                      <th className="text-right px-3 py-2 font-medium text-muted-foreground w-24">
                        Total
                      </th>
                      <th className="w-10" />
                    </tr>
                  </thead>
                  <tbody>
                    {lineItems.map((li, idx) => (
                      <tr
                        key={idx}
                        className="border-b last:border-0 hover:bg-muted/30"
                      >
                        <td className="px-3 py-1.5 text-muted-foreground tabular-nums">
                          {li.line_number}
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            value={li.item_code}
                            onChange={(e) =>
                              updateLineItem(idx, "item_code", e.target.value)
                            }
                            className="h-8 text-xs font-mono"
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            value={li.item_description}
                            onChange={(e) =>
                              updateLineItem(
                                idx,
                                "item_description",
                                e.target.value,
                              )
                            }
                            className="h-8 text-xs"
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            type="number"
                            value={li.quantity}
                            onChange={(e) =>
                              updateLineItem(idx, "quantity", e.target.value)
                            }
                            className="h-8 text-xs text-right"
                            step="any"
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            type="number"
                            value={li.unit_price}
                            onChange={(e) =>
                              updateLineItem(
                                idx,
                                "unit_price",
                                e.target.value,
                              )
                            }
                            className="h-8 text-xs text-right"
                            step="any"
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <Input
                            type="number"
                            value={li.total_price}
                            onChange={(e) =>
                              updateLineItem(
                                idx,
                                "total_price",
                                e.target.value,
                              )
                            }
                            className="h-8 text-xs text-right"
                            step="any"
                          />
                        </td>
                        <td className="px-2 py-1.5">
                          <button
                            onClick={() => removeLineItem(idx)}
                            className="text-muted-foreground hover:text-destructive transition-colors"
                            title="Remove row"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                        </td>
                      </tr>
                    ))}
                    {lineItems.length === 0 && (
                      <tr>
                        <td
                          colSpan={7}
                          className="text-center py-6 text-sm text-muted-foreground"
                        >
                          No line items. Click "Add Row" to add one.
                        </td>
                      </tr>
                    )}
                  </tbody>
                </table>
              </div>
            </CardContent>
          </Card>

          <Card className="border shadow-sm">
            <CardHeader className="pb-3">
              <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                Financial Summary
              </CardTitle>
            </CardHeader>
            <CardContent>
              <div className="grid grid-cols-2 gap-4">
                <div className="space-y-1.5">
                  <Label htmlFor="subtotal">Subtotal</Label>
                  <Input
                    id="subtotal"
                    type="number"
                    value={form.subtotal}
                    onChange={(e) => updateField("subtotal", e.target.value)}
                    step="any"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="tax_amount">Tax Amount</Label>
                  <Input
                    id="tax_amount"
                    type="number"
                    value={form.tax_amount}
                    onChange={(e) => updateField("tax_amount", e.target.value)}
                    step="any"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="discount_amount">Discount</Label>
                  <Input
                    id="discount_amount"
                    type="number"
                    value={form.discount_amount}
                    onChange={(e) =>
                      updateField("discount_amount", e.target.value)
                    }
                    step="any"
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="total_amount">Total Amount</Label>
                  <Input
                    id="total_amount"
                    type="number"
                    value={form.total_amount}
                    onChange={(e) =>
                      updateField("total_amount", e.target.value)
                    }
                    step="any"
                    className="font-semibold"
                  />
                </div>
              </div>
            </CardContent>
          </Card>

          {score?.breakdown && score.breakdown.length > 0 && (
            <Card className="border shadow-sm">
              <CardHeader className="pb-3">
                <CardTitle className="text-sm font-semibold text-muted-foreground uppercase tracking-wider">
                  Quality Score Breakdown
                </CardTitle>
              </CardHeader>
              <CardContent className="p-0">
                <div className="divide-y">
                  {score.breakdown.map((entry) => (
                    <div
                      key={entry.field}
                      className="flex items-center justify-between px-4 py-2 text-sm"
                    >
                      <div className="flex items-center gap-2">
                        {entry.actual_score === entry.max_score ? (
                          <CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />
                        ) : (
                          <AlertCircle className="h-3.5 w-3.5 text-amber-500" />
                        )}
                        <span className="text-foreground">{entry.field}</span>
                      </div>
                      <div className="flex items-center gap-3">
                        <span className="text-xs text-muted-foreground">
                          {entry.reason}
                        </span>
                        <span className="text-xs font-medium tabular-nums w-10 text-right">
                          {entry.actual_score}/{entry.max_score}
                        </span>
                      </div>
                    </div>
                  ))}
                </div>
              </CardContent>
            </Card>
          )}

          <div className="flex flex-wrap gap-3 pt-2">
            {canDeletePO && (
              <Button
                type="button"
                variant="destructive"
                onClick={() => {
                  setDeleteError(null);
                  setShowDeleteConfirm(true);
                }}
                disabled={submitting || deleting}
                className="gap-2"
              >
                <Trash2 className="h-4 w-4" />
                Delete PO
              </Button>
            )}
            <Button
              onClick={handleSubmit}
              disabled={submitting || deleting}
              className="gap-2"
            >
              {submitting ? (
                <>
                  <LoadingSpinner
                    size={16}
                    className="text-primary-foreground"
                  />
                  Submitting…
                </>
              ) : (
                <>
                  <Send className="h-4 w-4" />
                  Submit Review
                </>
              )}
            </Button>
          </div>
        </div>
      </div>
    </div>
    {showDeleteConfirm && (
      <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 px-4">
        <Card className="w-full max-w-md border shadow-lg">
          <CardHeader>
            <CardTitle>Delete Purchase Order?</CardTitle>
          </CardHeader>
          <CardContent className="space-y-4">
            <p className="text-sm text-muted-foreground">
              Are you sure you want to delete this PO?
              <br />
              This action cannot be undone.
            </p>

            {deleteError && (
              <div className="flex items-start gap-3 rounded-lg border border-destructive/50 bg-destructive/5 px-4 py-3">
                <AlertCircle className="h-5 w-5 text-destructive shrink-0 mt-0.5" />
                <p className="text-sm text-destructive">{deleteError}</p>
              </div>
            )}

            <div className="flex justify-end gap-3">
              <Button
                type="button"
                variant="outline"
                onClick={() => setShowDeleteConfirm(false)}
                disabled={deleting}
              >
                Cancel
              </Button>
              <Button
                type="button"
                variant="destructive"
                onClick={handleDeletePurchaseOrder}
                disabled={deleting}
              >
                {deleting ? (
                  <>
                    <LoadingSpinner
                      size={16}
                      className="text-destructive-foreground"
                    />
                    Deleting…
                  </>
                ) : (
                  "Delete"
                )}
              </Button>
            </div>
          </CardContent>
        </Card>
      </div>
    )}
    </>
  );
}

/* ------------------------------------------------------------------ */
/*  Tab label helper                                                  */
/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */

/* ------------------------------------------------------------------ */
/*  Main review page with tabs                                        */
/* ------------------------------------------------------------------ */

import { useSearchParams } from "react-router-dom";
import { poService } from "@/features/purchase-orders/services/poService";

export function ReviewPage() {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const poIdStr = searchParams.get("poId");
  const poNumberParam = searchParams.get("poNumber");

  const [loading, setLoading] = useState(true);
  const [activeItem, setActiveItem] = useState<ExtractionResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  // Auto-fetch the PO by the poId param
  useEffect(() => {
    const mapPOToReviewItem = (po: Awaited<ReturnType<typeof poService.getPurchaseOrder>>): ExtractionResult => ({
      document_type: "po",
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      score: { percentage: 0, requires_review: true, breakdown: [] } as any,
      extracted_data: {
        po_number: po.po_number,
        status: po.status,
        currency: po.currency,
        po_date: po.po_date,
        subtotal: po.subtotal?.toString(),
        tax_amount: po.tax_amount?.toString(),
        discount_amount: po.discount_amount?.toString(),
        total_amount: po.total_amount?.toString(),
        vendor_name: po.vendor?.vendor_name,
        vendor_email: po.vendor?.vendor_email,
        vendor_phone: po.vendor?.vendor_phone,
        vendor_tax_id: po.vendor?.gst_number,
        vendor_address: po.vendor?.vendor_address,
        line_items: po.line_items?.map((li) => ({
          line_number: li.line_number,
          item_code: li.item_code,
          item_description: li.item_description,
          quantity: li.quantity?.toString(),
          unit_price: li.unit_price?.toString(),
          total_price: li.total_price?.toString(),
        })),
      },
      stored_record: { id: po.id, po_number: po.po_number },
      file_url: po.file_url,
      auto_generated_fields: [],
    });

    const fetchById = async (id: number) => {
      const po = await poService.getPurchaseOrder(id);
      if (po.status?.toUpperCase() !== "PENDING") {
        navigate(`/purchase-orders/${po.id}`, { replace: true });
        return;
      }
      sessionStorage.setItem("active_review_id", String(po.id));
      setActiveItem(mapPOToReviewItem(po));
    };

    const fetchByNumber = async (poNumber: string) => {
      const results = await reviewService.searchPurchaseOrders(poNumber);
      const matched = results.find(
        (po) => po.po_number.toLowerCase() === poNumber.toLowerCase(),
      );
      if (!matched) {
        throw new Error("PO_NOT_FOUND_BY_NUMBER");
      }
      navigate(`/review?poId=${matched.id}`, { replace: true });
    };

    const fetchPO = async () => {
      try {
        setLoading(true);
        setError(null);

        const id = poIdStr ? parseInt(poIdStr, 10) : NaN;
        if (!Number.isNaN(id)) {
          const lockedId = sessionStorage.getItem("active_review_id");
          if (lockedId && lockedId !== String(id)) {
            navigate(`/review?poId=${lockedId}`, { replace: true });
            return;
          }

          try {
            await fetchById(id);
            return;
          } catch {
            sessionStorage.removeItem("active_review_id");
            if (poNumberParam) {
              await fetchByNumber(poNumberParam);
              return;
            }
            throw new Error("PO_NOT_FOUND");
          }
        }

        if (poNumberParam) {
          await fetchByNumber(poNumberParam);
          return;
        }

        navigate("/upload", { replace: true });
      } catch (err: unknown) {
        console.error("Failed to load PO for review", err);
        setError("Failed to load the requested document.");
      } finally {
        setLoading(false);
      }
    };

    void fetchPO();
  }, [poIdStr, poNumberParam, navigate]);

  const handleSubmitted = () => {
    sessionStorage.removeItem("active_review_id");
    if (activeItem?.stored_record?.id) {
       navigate(`/purchase-orders/${activeItem.stored_record.id}`);
    } else {
       navigate("/purchase-orders");
    }
  };

  const handleDeleted = (message: string) => {
    sessionStorage.removeItem("active_review_id");
    navigate("/purchase-orders", {
      replace: true,
      state: { successMessage: message },
    });
  };

  const handleCancel = () => {
    sessionStorage.removeItem("active_review_id");
    if (window.history.length > 2) {
      navigate(-1);
    } else {
      navigate("/upload");
    }
  };

  if (loading) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-4">
        <LoadingSpinner size={32} />
        <p className="text-muted-foreground text-sm">
          Loading document for review…
        </p>
      </div>
    );
  }

  if (error) {
     return (
        <div className="flex flex-col items-center justify-center h-64 gap-4">
            <AlertCircle className="h-12 w-12 text-destructive opacity-60" />
            <p className="text-muted-foreground">
                {error}
            </p>
            <Button variant="outline" onClick={() => navigate("/purchase-orders")}>
                <ArrowLeft className="h-4 w-4 mr-2" />
                Go to Purchase Orders
            </Button>
        </div>
     );
  }

  if (!activeItem) {
    return (
      <div className="flex flex-col items-center justify-center h-64 gap-4">
        <CheckCircle2 className="h-12 w-12 text-emerald-500 opacity-60" />
        <p className="text-muted-foreground">
          No document loaded.
        </p>
        <Button variant="outline" onClick={handleCancel}>
          <ArrowLeft className="h-4 w-4 mr-2" />
          Upload a Document
        </Button>
      </div>
    );
  }

  const documentName = activeItem.stored_record?.po_number ?? (activeItem.extracted_data?.po_number as string) ?? activeItem.stored_record?.id ?? "Unknown PO";

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-4">
        <Button
          variant="ghost"
          size="sm"
          onClick={handleCancel}
        >
          <ArrowLeft className="h-4 w-4 mr-1" />
          Cancel
        </Button>
        <div className="flex-1">
          <h1 className="text-2xl font-bold tracking-tight">
            Review Purchase Order
          </h1>
          <div className="flex items-center gap-2 mt-0.5">
             <span className="font-medium text-foreground text-sm">PO-{documentName}</span>
             <span className="text-muted-foreground text-sm">&bull;</span>
             <Badge variant="warning" className="uppercase text-xs tracking-wider">Status: Pending</Badge>
          </div>
        </div>
      </div>

      <DocumentReviewForm
        key={`review-${activeItem.stored_record?.id}`}
        item={activeItem}
        onSubmitted={handleSubmitted}
        onDeleted={handleDeleted}
      />
    </div>
  );
}
